version: '3'

services:
  # MySQL
  mydb:
    build: ./mysql
    container_name: mydb
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sandbox
#      MYSQL_USER: sandbox_user
#      MYSQL_PASSWORD: passpass
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    volumes:
      - '/server/mysql/data:/var/lib/mysql'
      - '/server/mysql/my.cnf:/etc/mysql/conf.d/my.cnf'
      - '/server/mysql/sql:/docker-entrypoint-initdb.d'
  myredis:
    build: ./redis
    container_name: "myredis"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /server/redis:/data
  myphp:
    build: ./php
    container_name: "myphp"
    privileged: true
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /server/www:/var/www/html
      - /server/php/php.ini:/usr/local/etc/php/php.ini
    links:
      - "mydb"
      - "myredis"
  mynginx:
    build: ./nginx
    container_name: "mynginx"
    privileged: true
    restart: always
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:81:81"
      - "0.0.0.0:443:443"
      - "0.0.0.0:555:555"
      - "0.0.0.0:500:500"
      - "0.0.0.0:800:800"
      - "0.0.0.0:801:801"
      - "0.0.0.0:802:802"
      - "0.0.0.0:803:803"
      - "0.0.0.0:804:804"
      - "0.0.0.0:805:805"
      - "0.0.0.0:806:806"
      - "0.0.0.0:807:807"
      - "0.0.0.0:808:808"
      - "0.0.0.0:810:810"
      - "0.0.0.0:813:813"
      - "0.0.0.0:843:843"
      - "0.0.0.0:844:844"
      - "0.0.0.0:887:887"
      - "0.0.0.0:888:888"
      - "0.0.0.0:882:882"
      - "0.0.0.0:880:880"
      - "0.0.0.0:872:872"
      - "0.0.0.0:893:893"
      - "0.0.0.0:895:895"
      - "0.0.0.0:876:876"
      - "0.0.0.0:877:877"
      - "0.0.0.0:879:879"
      - "0.0.0.0:701:701"
      - "0.0.0.0:750:750"
      - "0.0.0.0:753:753"
      - "0.0.0.0:756:756"
      - "0.0.0.0:834:834"
      - "0.0.0.0:835:835"
      - "0.0.0.0:836:836"
      - "0.0.0.0:865:865"
      - "0.0.0.0:901:901"
      - "0.0.0.0:930:930"
      - "0.0.0.0:931:931"
      - "0.0.0.0:932:932"
      - "0.0.0.0:9322:9322"
      - "0.0.0.0:933:933"
      - "0.0.0.0:934:934"
      - "0.0.0.0:935:935"
      - "0.0.0.0:936:936"
      - "0.0.0.0:8761:8761"
      - "0.0.0.0:4300:4300"
      - "0.0.0.0:5000:5000"
      - "0.0.0.0:2501:2501"
      - "0.0.0.0:2511:2511"
      - "0.0.0.0:2512:2512"
      - "0.0.0.0:2513:2513"
      - "0.0.0.0:2332:2332"
      - "0.0.0.0:1921:1921"
      - "0.0.0.0:5622:5622"
    links:
      - "myphp"
    volumes:
      - /server/www:/usr/share/nginx/html
      - /server/nginx:/etc/nginx
      - /server/logs/nginx.logs:/var/log/nginx
  mygogs:
    build: ./gogs
    container_name: "mygogs"
    privileged: true
    restart: always
    ports:
      - "10022:22"
      - "10080:3000"
    volumes:
      - /server/gogs:/data
    links:
      - "mydb"
